# fly.toml app configuration file generated for da-course-20230811 on 2023-08-11T12:25:24-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "da-course-20230811"
primary_region = "eze"

[build]
  image = "lionelherrerobattista/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dcou60a7i"
  CloudinarySettings__ApiKey="379751755363377"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
